"""Generated baseline for the permission-ledger expectations.

WHY THIS EXISTS. ``test_perm_ledger`` and ``test_perm_ledger_wiring`` pin the exact set
of IAM actions the shipped role is missing, and the exact set of checks that are blocked
as a result. Pinning them is right: the permission surface is the thing a customer has to
approve, so it must never widen without somebody deciding it should.

Hand-maintaining those lists was the problem. They are sorted, they are long, and every
new batch of checks inserts entries in the middle of them. Over three service-coverage
batches that produced the same class of mistake repeatedly -- ``rds`` sorts before
``s3``, ``codebuild`` before ``ec2``, and a block-detection pattern that did not allow a
trailing bracket silently orphaned the last entry of every list it touched. Twice the
lists ended up corrupted and had to be restored from git.

So the data is now GENERATED and committed, exactly like ``test_suite_ratchet``. The
ratchet property survives -- the numbers change only when somebody runs ``--update``, and
the change lands in the diff where a reviewer sees it -- while the sorting, the commas
and the brackets stop being anybody's problem::

    python tests/perm_ledger_baseline.py --update

This is deliberately NOT a self-deriving assertion. Computing the expected value from the
ledger at test time would make the test tautological and delete the only thing it was
protecting.
"""
from __future__ import annotations

import io
import os
import pathlib
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# ─────────────────────────────────────────────────────────────────────────────
# Generated, never typed by hand: python tests/perm_ledger_baseline.py --update
BASELINE = {
    "granted_fixture": {
        "missing_actions": [
            "account:GetAlternateContact",
            "account:GetContactInformation",
            "acm-pca:GetPolicy",
            "acm-pca:ListCertificateAuthorities",
            "aoss:BatchGetCollection",
            "aoss:GetAccessPolicy",
            "aoss:GetSecurityPolicy",
            "aoss:ListAccessPolicies",
            "aoss:ListCollections",
            "aoss:ListSecurityPolicies",
            "apprunner:DescribeService",
            "apprunner:ListServices",
            "aps:DescribeWorkspace",
            "aps:ListWorkspaces",
            "autoscaling:DescribeAutoScalingGroups",
            "backup:ListProtectedResources",
            "batch:DescribeJobDefinitions",
            "bedrock-agentcore:GetAgentRuntime",
            "bedrock-agentcore:GetGateway",
            "bedrock-agentcore:GetGatewayTarget",
            "bedrock-agentcore:GetMemory",
            "bedrock-agentcore:GetTokenVault",
            "bedrock-agentcore:GetWorkloadIdentity",
            "bedrock-agentcore:ListAgentRuntimes",
            "bedrock-agentcore:ListApiKeyCredentialProviders",
            "bedrock-agentcore:ListBrowsers",
            "bedrock-agentcore:ListCodeInterpreters",
            "bedrock-agentcore:ListGatewayTargets",
            "bedrock-agentcore:ListGateways",
            "bedrock-agentcore:ListMemories",
            "bedrock-agentcore:ListOauth2CredentialProviders",
            "bedrock-agentcore:ListRegistries",
            "bedrock-agentcore:ListRegistryRecords",
            "bedrock-agentcore:ListWorkloadIdentities",
            "bedrock:GetAgentActionGroup",
            "bedrock:GetDataSource",
            "bedrock:GetGuardrail",
            "bedrock:GetKnowledgeBase",
            "cloudformation:DescribeStacks",
            "cloudformation:GetStackPolicy",
            "cloudformation:ListStacks",
            "cloudhsm:DescribeClusters",
            "cloudhsm:GetResourcePolicy",
            "cloudtrail:DescribeTrails",
            "cloudtrail:GetEventSelectors",
            "cloudtrail:LookupEvents",
            "codeartifact:GetDomainPermissionsPolicy",
            "codeartifact:GetRepositoryPermissionsPolicy",
            "codeartifact:ListDomains",
            "codeartifact:ListRepositories",
            "codebuild:BatchGetProjects",
            "codebuild:ListProjects",
            "codeguru-profiler:GetPolicy",
            "codeguru-profiler:ListProfilingGroups",
            "ds:DescribeDirectories",
            "ds:DescribeLDAPSSettings",
            "ds:DescribeSharedDirectories",
            "dsql:GetCluster",
            "dsql:ListClusters",
            "ec2:DescribeImages",
            "ec2:DescribeInstanceTypes",
            "ec2:DescribeInstances",
            "ec2:DescribeNetworkInterfaces",
            "ec2:DescribeSecurityGroups",
            "ec2:DescribeVpcEndpoints",
            "ec2:DescribeVpcPeeringConnections",
            "ecr-public:DescribeRepositories",
            "ecr-public:GetRepositoryPolicy",
            "ecs:DescribeClusters",
            "ecs:DescribeServices",
            "ecs:DescribeTaskDefinition",
            "ecs:DescribeTaskSets",
            "ecs:ListClusters",
            "ecs:ListServices",
            "ecs:ListTaskDefinitions",
            "elasticache:DescribeReplicationGroups",
            "elasticbeanstalk:DescribeConfigurationSettings",
            "elasticbeanstalk:DescribeEnvironments",
            "elasticmapreduce:DescribeCluster",
            "elasticmapreduce:GetBlockPublicAccessConfiguration",
            "elasticmapreduce:ListClusters",
            "fms:GetNotificationChannel",
            "fms:GetPolicy",
            "fms:ListPolicies",
            "glue:GetDataCatalogEncryptionSettings",
            "glue:GetDevEndpoints",
            "grafana:DescribeWorkspace",
            "grafana:ListWorkspaces",
            "iam:GetAccountAuthorizationDetails",
            "iam:GetPolicyVersion",
            "iam:GetRole",
            "iam:GetRolePolicy",
            "iam:ListAccessKeys",
            "iam:ListAttachedRolePolicies",
            "iam:ListAttachedUserPolicies",
            "iam:ListEntitiesForPolicy",
            "iam:ListInstanceProfilesForRole",
            "iam:ListOpenIDConnectProviders",
            "iam:ListOrganizationsFeatures",
            "iam:ListRolePolicies",
            "iam:ListRoles",
            "iam:ListSAMLProviders",
            "iam:ListUserPolicies",
            "iam:ListVirtualMFADevices",
            "imagebuilder:GetDistributionConfiguration",
            "imagebuilder:GetImagePolicy",
            "imagebuilder:GetImageRecipe",
            "imagebuilder:ListDistributionConfigurations",
            "imagebuilder:ListImageRecipes",
            "imagebuilder:ListImages",
            "iot:DescribeCACertificate",
            "iot:GetPolicy",
            "iot:GetV2LoggingOptions",
            "iot:ListCACertificates",
            "iot:ListPolicies",
            "iotfleetwise:GetEncryptionConfiguration",
            "iotfleetwise:GetLoggingOptions",
            "iotmanagedintegrations:GetDefaultEncryptionConfiguration",
            "iotsitewise:DescribeDefaultEncryptionConfiguration",
            "iotsitewise:DescribeLoggingOptions",
            "lakeformation:GetDataLakeSettings",
            "lakeformation:ListPermissions",
            "lambda:GetFunctionRecursionConfig",
            "lambda:GetLayerVersionPolicy",
            "lambda:ListFunctions",
            "lambda:ListLayers",
            "lightsail:GetBuckets",
            "lightsail:GetInstancePortStates",
            "lightsail:GetInstances",
            "lightsail:GetRelationalDatabases",
            "managedblockchain:GetMember",
            "managedblockchain:ListMembers",
            "mediapackagev2:GetChannelPolicy",
            "mediapackagev2:ListChannelGroups",
            "memorydb:DescribeACLs",
            "memorydb:DescribeClusters",
            "memorydb:DescribeUsers",
            "mpa:GetApprovalTeam",
            "mpa:ListApprovalTeams",
            "network-firewall:DescribeFirewall",
            "network-firewall:DescribeFirewallPolicy",
            "network-firewall:DescribeLoggingConfiguration",
            "network-firewall:ListFirewalls",
            "networkmanager:DescribeGlobalNetworks",
            "networkmanager:GetResourcePolicy",
            "organizations:DescribeOrganization",
            "organizations:DescribePolicy",
            "organizations:DescribeResourcePolicy",
            "organizations:ListAWSServiceAccessForOrganization",
            "organizations:ListAccounts",
            "organizations:ListAccountsForParent",
            "organizations:ListDelegatedAdministrators",
            "organizations:ListDelegatedServicesForAccount",
            "organizations:ListOrganizationalUnitsForParent",
            "organizations:ListPolicies",
            "organizations:ListPoliciesForTarget",
            "organizations:ListRoots",
            "payment-cryptography:GetKey",
            "payment-cryptography:ListKeys",
            "quicksight:DescribeAccountSettings",
            "rds:DescribeDBClusterParameters",
            "rds:DescribeDBClusterSnapshotAttributes",
            "rds:DescribeDBClusterSnapshots",
            "rds:DescribeDBClusters",
            "rds:DescribeDBInstances",
            "rds:DescribeDBParameters",
            "rds:DescribeEventSubscriptions",
            "rds:DescribePendingMaintenanceActions",
            "s3:GetBucketLogging",
            "s3:GetBucketPolicy",
            "s3:GetBucketVersioning",
            "s3tables:GetTableBucketEncryption",
            "s3tables:GetTableBucketPolicy",
            "s3tables:ListTableBuckets",
            "s3vectors:GetVectorBucket",
            "s3vectors:GetVectorBucketPolicy",
            "s3vectors:ListVectorBuckets",
            "ses:GetTrafficPolicy",
            "ses:ListTrafficPolicies",
            "ssm:ListInventoryEntries",
            "sso:GetInlinePolicyForPermissionSet",
            "sso:ListInstances",
            "sso:ListPermissionSets",
            "storagegateway:DescribeNFSFileShares",
            "storagegateway:DescribeSMBFileShares",
            "storagegateway:ListFileShares",
            "timestream:ListDatabases",
            "timestream:ListTables",
            "transfer:DescribeServer",
            "transfer:ListServers",
            "verifiedpermissions:GetPolicyStore",
            "verifiedpermissions:ListPolicyStores",
            "vpc-lattice:GetAuthPolicy",
            "vpc-lattice:GetService",
            "vpc-lattice:ListServices",
            "wickr:GetNetworkSettings",
            "wickr:ListNetworks",
            "workmail:GetDefaultRetentionPolicy",
            "workmail:ListAccessControlRules",
            "workmail:ListMobileDeviceAccessRules",
            "workmail:ListOrganizations",
            "workspaces-web:GetPortal",
            "workspaces-web:ListPortals",
            "xray:GetEncryptionConfig",
        ],
        "blocked_checks": [
            "ACCT-01",
            "ACCT-02",
            "AGC-01",
            "AGC-02",
            "AGC-03",
            "AGC-04",
            "AGC-05",
            "AGC-06",
            "AGC-07",
            "AGC-08",
            "AGT-03",
            "AGT-04",
            "AGY-01",
            "AGY-02",
            "AGY-03",
            "AIGRD-01",
            "AIGRD-02",
            "AIGRD-04",
            "AILOG-04",
            "AILOG-05",
            "AILOG-06",
            "AL2-01",
            "AL2-02",
            "AL2-03",
            "AMEM-02",
            "AMI-04",
            "AMI-05",
            "AMP-01",
            "APRUN-01",
            "ASG-02",
            "AUR-06",
            "AUR-07",
            "AUR-08",
            "BATCH-01",
            "BATCH-02",
            "CART-01",
            "CB-01",
            "CB-02",
            "CGP-01",
            "CREDEXP-01",
            "DDB-06",
            "DDB-07",
            "DIRSVC-01",
            "DIRSVC-02",
            "DOCDB-01",
            "DOCDB-02",
            "DOCDB-03",
            "DOCDB-04",
            "DOCDB-05",
            "DOCDB-06",
            "DOCDB-07",
            "DOCDB-08",
            "DOCDB-09",
            "DOCDB-10",
            "DSQL-01",
            "EB-01",
            "EB-02",
            "EB-03",
            "EB-04",
            "EC2-10",
            "EC2-11",
            "EC2-12",
            "EC2-13",
            "EC2-14",
            "EC2-15",
            "EC2-16",
            "EC2-17",
            "EC2-18",
            "ECRPUB-01",
            "ECS-09",
            "ECS-10",
            "ECS-11",
            "ECS-12",
            "ECS-13",
            "ECS-14",
            "ECS-15",
            "ECS-16",
            "ECS-17",
            "ELC-07",
            "ELC-08",
            "ELC-09",
            "EMR-01",
            "EMR-02",
            "FARGATE-03",
            "FMS-01",
            "FMS-02",
            "FW-01",
            "FW-02",
            "GLUE-01",
            "GLUE-02",
            "GRF-01",
            "HSM-01",
            "HSM-02",
            "IAM-11",
            "IAM-12",
            "IAM-13",
            "IAM-14",
            "IAM-15",
            "IMGB-01",
            "IMGB-02",
            "IMGB-03",
            "IMI-01",
            "IOT-01",
            "IOT-02",
            "IOT-03",
            "LATT-01",
            "LATT-02",
            "LF-01",
            "LF-02",
            "LMB-10",
            "LMB-11",
            "LMB-12",
            "LMB-13",
            "LMB-14",
            "LMB-15",
            "LMB-16",
            "LMB-17",
            "LOG-11",
            "LOG-12",
            "LSAIL-01",
            "LSAIL-02",
            "LSAIL-03",
            "LSAIL-04",
            "LSAIL-05",
            "LSAIL-06",
            "LSAIL-07",
            "MART-01",
            "MBC-01",
            "MCP-01",
            "MCP-02",
            "MCP-03",
            "MCP-04",
            "MCP-06",
            "MDB-01",
            "MDB-02",
            "MDB-03",
            "MDB-04",
            "MDB-05",
            "MDB-06",
            "MDB-07",
            "MM-01",
            "MPA-01",
            "MPV-01",
            "NEP-01",
            "NEP-02",
            "NEP-03",
            "NEP-04",
            "NEP-05",
            "NEP-06",
            "NEP-07",
            "NEP-08",
            "NEP-09",
            "NEP-10",
            "NEP-11",
            "NFW-01",
            "NFW-02",
            "NFW-03",
            "NHI-01",
            "NHI-02",
            "NHI-03",
            "NHI-04",
            "NHI-05",
            "NITRO-01",
            "NITRO-02",
            "NWM-01",
            "ORG-01",
            "ORG-02",
            "ORG-03",
            "ORG-04",
            "ORG-05",
            "ORG-06",
            "PAY-01",
            "PCA-01",
            "PERIM-01",
            "PERIM-02",
            "PERIM-03",
            "QS-01",
            "RDS-14",
            "S3-11",
            "S3T-01",
            "S3T-02",
            "SGW-01",
            "SGW-02",
            "SHAI-01",
            "SHAI-02",
            "SHAI-03",
            "SSO-01",
            "STACK-01",
            "STACK-02",
            "SW-01",
            "SW-02",
            "TFLOW-01",
            "TS-01",
            "TS-02",
            "TS-03",
            "TS-04",
            "VEC-01",
            "VEC-02",
            "VEC-03",
            "VEC-04",
            "VEC-05",
            "VEC-06",
            "VEC-07",
            "VP-01",
            "VP-02",
            "VPC-07",
            "VPC-08",
            "WKR-01",
            "WM-01",
            "WM-02",
            "WM-03",
            "WSW-01",
            "WSW-02",
            "XFER-01",
            "XFER-02",
            "XFER-03",
            "XRAY-01",
        ],
        "annotated_policy_rows": 204,
    },
    "shipped_role": {
        "missing_actions": [
            "account:GetAlternateContact",
            "account:GetContactInformation",
            "acm-pca:GetPolicy",
            "acm-pca:ListCertificateAuthorities",
            "aoss:BatchGetCollection",
            "aoss:GetAccessPolicy",
            "aoss:GetSecurityPolicy",
            "aoss:ListAccessPolicies",
            "aoss:ListCollections",
            "aoss:ListSecurityPolicies",
            "apprunner:DescribeService",
            "apprunner:ListServices",
            "aps:DescribeWorkspace",
            "aps:ListWorkspaces",
            "autoscaling:DescribeAutoScalingGroups",
            "backup:ListProtectedResources",
            "batch:DescribeJobDefinitions",
            "bedrock-agentcore:GetAgentRuntime",
            "bedrock-agentcore:GetGateway",
            "bedrock-agentcore:GetGatewayTarget",
            "bedrock-agentcore:GetMemory",
            "bedrock-agentcore:GetTokenVault",
            "bedrock-agentcore:GetWorkloadIdentity",
            "bedrock-agentcore:ListAgentRuntimes",
            "bedrock-agentcore:ListApiKeyCredentialProviders",
            "bedrock-agentcore:ListBrowsers",
            "bedrock-agentcore:ListCodeInterpreters",
            "bedrock-agentcore:ListGatewayTargets",
            "bedrock-agentcore:ListGateways",
            "bedrock-agentcore:ListMemories",
            "bedrock-agentcore:ListOauth2CredentialProviders",
            "bedrock-agentcore:ListRegistries",
            "bedrock-agentcore:ListRegistryRecords",
            "bedrock-agentcore:ListWorkloadIdentities",
            "bedrock:GetAgentActionGroup",
            "bedrock:GetDataSource",
            "bedrock:GetGuardrail",
            "bedrock:GetKnowledgeBase",
            "cloudformation:DescribeStacks",
            "cloudformation:GetStackPolicy",
            "cloudformation:ListStacks",
            "cloudhsm:DescribeClusters",
            "cloudhsm:GetResourcePolicy",
            "cloudtrail:DescribeTrails",
            "cloudtrail:GetEventSelectors",
            "cloudtrail:LookupEvents",
            "codeartifact:GetDomainPermissionsPolicy",
            "codeartifact:GetRepositoryPermissionsPolicy",
            "codeartifact:ListDomains",
            "codeartifact:ListRepositories",
            "codebuild:BatchGetProjects",
            "codebuild:ListProjects",
            "codeguru-profiler:GetPolicy",
            "codeguru-profiler:ListProfilingGroups",
            "ds:DescribeDirectories",
            "ds:DescribeLDAPSSettings",
            "ds:DescribeSharedDirectories",
            "dsql:GetCluster",
            "dsql:ListClusters",
            "ecr-public:DescribeRepositories",
            "ecr-public:GetRepositoryPolicy",
            "ecs:DescribeClusters",
            "ecs:DescribeServices",
            "ecs:DescribeTaskDefinition",
            "ecs:DescribeTaskSets",
            "ecs:ListClusters",
            "ecs:ListServices",
            "ecs:ListTaskDefinitions",
            "elasticache:DescribeReplicationGroups",
            "elasticbeanstalk:DescribeConfigurationSettings",
            "elasticbeanstalk:DescribeEnvironments",
            "elasticmapreduce:DescribeCluster",
            "elasticmapreduce:GetBlockPublicAccessConfiguration",
            "elasticmapreduce:ListClusters",
            "fms:GetNotificationChannel",
            "fms:GetPolicy",
            "fms:ListPolicies",
            "glue:GetDataCatalogEncryptionSettings",
            "glue:GetDevEndpoints",
            "grafana:DescribeWorkspace",
            "grafana:ListWorkspaces",
            "imagebuilder:GetDistributionConfiguration",
            "imagebuilder:GetImagePolicy",
            "imagebuilder:GetImageRecipe",
            "imagebuilder:ListDistributionConfigurations",
            "imagebuilder:ListImageRecipes",
            "imagebuilder:ListImages",
            "iot:DescribeCACertificate",
            "iot:GetPolicy",
            "iot:GetV2LoggingOptions",
            "iot:ListCACertificates",
            "iot:ListPolicies",
            "iotfleetwise:GetEncryptionConfiguration",
            "iotfleetwise:GetLoggingOptions",
            "iotmanagedintegrations:GetDefaultEncryptionConfiguration",
            "iotsitewise:DescribeDefaultEncryptionConfiguration",
            "iotsitewise:DescribeLoggingOptions",
            "lakeformation:GetDataLakeSettings",
            "lakeformation:ListPermissions",
            "lambda:GetFunctionRecursionConfig",
            "lambda:GetLayerVersionPolicy",
            "lambda:ListFunctions",
            "lambda:ListLayers",
            "lightsail:GetBuckets",
            "lightsail:GetInstancePortStates",
            "lightsail:GetInstances",
            "lightsail:GetRelationalDatabases",
            "managedblockchain:GetMember",
            "managedblockchain:ListMembers",
            "mediapackagev2:GetChannelPolicy",
            "mediapackagev2:ListChannelGroups",
            "memorydb:DescribeACLs",
            "memorydb:DescribeClusters",
            "memorydb:DescribeUsers",
            "mpa:GetApprovalTeam",
            "mpa:ListApprovalTeams",
            "network-firewall:DescribeFirewall",
            "network-firewall:DescribeFirewallPolicy",
            "network-firewall:DescribeLoggingConfiguration",
            "network-firewall:ListFirewalls",
            "networkmanager:DescribeGlobalNetworks",
            "networkmanager:GetResourcePolicy",
            "organizations:DescribeOrganization",
            "organizations:DescribePolicy",
            "organizations:DescribeResourcePolicy",
            "organizations:ListAWSServiceAccessForOrganization",
            "organizations:ListAccounts",
            "organizations:ListAccountsForParent",
            "organizations:ListDelegatedAdministrators",
            "organizations:ListDelegatedServicesForAccount",
            "organizations:ListOrganizationalUnitsForParent",
            "organizations:ListPolicies",
            "organizations:ListPoliciesForTarget",
            "organizations:ListRoots",
            "payment-cryptography:GetKey",
            "payment-cryptography:ListKeys",
            "quicksight:DescribeAccountSettings",
            "rds:DescribeDBClusterParameters",
            "rds:DescribeDBClusterSnapshotAttributes",
            "rds:DescribeDBClusterSnapshots",
            "rds:DescribeDBClusters",
            "rds:DescribeDBInstances",
            "rds:DescribeDBParameters",
            "rds:DescribeEventSubscriptions",
            "rds:DescribePendingMaintenanceActions",
            "s3:GetBucketLogging",
            "s3:GetBucketPolicy",
            "s3:GetBucketVersioning",
            "s3tables:GetTableBucketEncryption",
            "s3tables:GetTableBucketPolicy",
            "s3tables:ListTableBuckets",
            "s3vectors:GetVectorBucket",
            "s3vectors:GetVectorBucketPolicy",
            "s3vectors:ListVectorBuckets",
            "ses:GetTrafficPolicy",
            "ses:ListTrafficPolicies",
            "ssm:ListInventoryEntries",
            "sso:GetInlinePolicyForPermissionSet",
            "sso:ListInstances",
            "sso:ListPermissionSets",
            "storagegateway:DescribeNFSFileShares",
            "storagegateway:DescribeSMBFileShares",
            "storagegateway:ListFileShares",
            "timestream:ListDatabases",
            "timestream:ListTables",
            "transfer:DescribeServer",
            "transfer:ListServers",
            "verifiedpermissions:GetPolicyStore",
            "verifiedpermissions:ListPolicyStores",
            "vpc-lattice:GetAuthPolicy",
            "vpc-lattice:GetService",
            "vpc-lattice:ListServices",
            "wickr:GetNetworkSettings",
            "wickr:ListNetworks",
            "workmail:GetDefaultRetentionPolicy",
            "workmail:ListAccessControlRules",
            "workmail:ListMobileDeviceAccessRules",
            "workmail:ListOrganizations",
            "workspaces-web:GetPortal",
            "workspaces-web:ListPortals",
            "xray:GetEncryptionConfig",
        ],
        "blocked_checks": [
            "ACCT-01",
            "ACCT-02",
            "AGC-01",
            "AGC-02",
            "AGC-03",
            "AGC-04",
            "AGC-05",
            "AGC-06",
            "AGC-07",
            "AGC-08",
            "AGT-03",
            "AGT-04",
            "AGY-01",
            "AGY-02",
            "AGY-03",
            "AIGRD-01",
            "AIGRD-02",
            "AIGRD-04",
            "AILOG-04",
            "AILOG-05",
            "AILOG-06",
            "AL2-01",
            "AL2-02",
            "AL2-03",
            "AMEM-02",
            "AMP-01",
            "APRUN-01",
            "ASG-02",
            "AUR-06",
            "AUR-07",
            "AUR-08",
            "BATCH-01",
            "CART-01",
            "CB-01",
            "CB-02",
            "CGP-01",
            "DIRSVC-01",
            "DIRSVC-02",
            "DOCDB-01",
            "DOCDB-02",
            "DOCDB-03",
            "DOCDB-04",
            "DOCDB-05",
            "DOCDB-06",
            "DOCDB-07",
            "DOCDB-08",
            "DOCDB-09",
            "DOCDB-10",
            "DSQL-01",
            "EB-01",
            "EB-02",
            "EB-03",
            "EB-04",
            "EC2-10",
            "EC2-11",
            "ECRPUB-01",
            "ECS-09",
            "ECS-10",
            "ECS-11",
            "ECS-12",
            "ECS-13",
            "ECS-14",
            "ECS-15",
            "ECS-16",
            "ECS-17",
            "ELC-07",
            "ELC-08",
            "ELC-09",
            "EMR-01",
            "EMR-02",
            "FARGATE-03",
            "FMS-01",
            "FMS-02",
            "FW-01",
            "FW-02",
            "GLUE-01",
            "GLUE-02",
            "GRF-01",
            "HSM-01",
            "HSM-02",
            "IAM-14",
            "IMGB-01",
            "IMGB-02",
            "IMGB-03",
            "IMI-01",
            "IOT-01",
            "IOT-02",
            "IOT-03",
            "LATT-01",
            "LATT-02",
            "LF-01",
            "LF-02",
            "LMB-10",
            "LMB-11",
            "LMB-12",
            "LMB-13",
            "LMB-14",
            "LMB-15",
            "LMB-16",
            "LMB-17",
            "LOG-11",
            "LOG-12",
            "LSAIL-01",
            "LSAIL-02",
            "LSAIL-03",
            "LSAIL-04",
            "LSAIL-05",
            "LSAIL-06",
            "LSAIL-07",
            "MART-01",
            "MBC-01",
            "MCP-01",
            "MCP-02",
            "MCP-03",
            "MCP-04",
            "MCP-06",
            "MDB-01",
            "MDB-02",
            "MDB-03",
            "MDB-04",
            "MDB-05",
            "MDB-06",
            "MDB-07",
            "MM-01",
            "MPA-01",
            "MPV-01",
            "NEP-01",
            "NEP-02",
            "NEP-03",
            "NEP-04",
            "NEP-05",
            "NEP-06",
            "NEP-07",
            "NEP-08",
            "NEP-09",
            "NEP-10",
            "NEP-11",
            "NFW-01",
            "NFW-02",
            "NFW-03",
            "NWM-01",
            "ORG-02",
            "ORG-03",
            "ORG-04",
            "ORG-05",
            "ORG-06",
            "PAY-01",
            "PCA-01",
            "PERIM-01",
            "PERIM-02",
            "PERIM-03",
            "QS-01",
            "RDS-14",
            "S3-11",
            "S3T-01",
            "S3T-02",
            "SGW-01",
            "SGW-02",
            "SHAI-01",
            "SHAI-02",
            "SSO-01",
            "STACK-01",
            "STACK-02",
            "SW-01",
            "SW-02",
            "TFLOW-01",
            "TS-01",
            "TS-02",
            "TS-04",
            "VEC-01",
            "VEC-02",
            "VEC-03",
            "VEC-04",
            "VEC-05",
            "VEC-06",
            "VEC-07",
            "VP-01",
            "VP-02",
            "WKR-01",
            "WM-01",
            "WM-02",
            "WM-03",
            "WSW-01",
            "WSW-02",
            "XFER-01",
            "XFER-02",
            "XFER-03",
            "XRAY-01",
        ],
        "annotated_policy_rows": 181,
    },
}
# ─────────────────────────────────────────────────────────────────────────────
# End generated block
# ─────────────────────────────────────────────────────────────────────────────

_START = "# Generated, never typed by hand: python tests/perm_ledger_baseline.py --update"
_END = "# End generated block"


def _fixtures():
    """The role fixtures the two ledger suites evaluate against.

    Read from the test modules rather than duplicated here: a second copy of a fixture
    is a second thing to keep in step, which is the failure this file exists to end."""
    import test_perm_ledger as TL
    import test_perm_ledger_wiring as TW

    return {
        "shipped_role": TL.SHIPPED_ROLE,
        "granted_fixture": [{
            "effect": "Allow", "actions": set(TW.GRANTED), "resources": {"*"},
            "not_resources": set(), "condition": None,
        }],
    }


def compute() -> dict:
    """Evaluate the ledger against each fixture and return the pinned facts."""
    from engine import aws_perm_ledger as L

    out = {}
    for name, role in _fixtures().items():
        led = L.evaluate(role)
        out[name] = {
            "missing_actions": list(led.missing_actions),
            "blocked_checks": sorted(led.blocked),
            "annotated_policy_rows": len(led.annotated_policy()),
        }
    return out


def _render(data: dict) -> str:
    lines = ["BASELINE = {"]
    for name in sorted(data):
        d = data[name]
        lines.append(f'    "{name}": {{')
        lines.append('        "missing_actions": [')
        for a in d["missing_actions"]:
            lines.append(f'            "{a}",')
        lines.append("        ],")
        lines.append('        "blocked_checks": [')
        for c in d["blocked_checks"]:
            lines.append(f'            "{c}",')
        lines.append("        ],")
        lines.append(f'        "annotated_policy_rows": {d["annotated_policy_rows"]},')
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines)


def update() -> dict:
    data = compute()
    p = pathlib.Path(__file__)
    src = io.open(p, encoding="utf-8").read()
    i = src.index(_START) + len(_START) + 1
    j = src.index(_END)
    # keep the decorative rule line that precedes the end marker
    j = src.rindex("# ────", i, j)
    io.open(p, "w", encoding="utf-8", newline="").write(
        src[:i] + _render(data) + "\n" + src[j:])
    return data


if __name__ == "__main__":
    if "--update" in sys.argv:
        d = update()
        for name in sorted(d):
            print(f"  {name}: {len(d[name]['missing_actions'])} missing action(s), "
                  f"{len(d[name]['blocked_checks'])} blocked check(s), "
                  f"{d[name]['annotated_policy_rows']} policy row(s)")
        print("baseline regenerated")
    else:
        print(__doc__)
        print("Run with --update to regenerate.")
