"""Phase-4 Slice-1 · B1 — multi-tenancy schema (SCHEMA 6->7) + ws-default seed/backfill.
Offline sqlite :memory:; POSTGRES_DDL parity as a string artifact."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import aws_state
import aws_state_dialect as dia
import cnapp_backend
from cnapp_registry import AccountRegistry

NEW_TABLES = {"workspaces", "workspace_members", "workspace_accounts",
              "platform_admins", "usage_events"}


def _reg():
    return AccountRegistry.open(":memory:")


def _tables(be):
    return {r[0] for r in be.query_all("SELECT name FROM sqlite_master WHERE type='table'")}


def test_schema_version_is_7():
    assert aws_state.SCHEMA_VERSION == 7


def test_migration_creates_multitenancy_tables():
    r = _reg()
    assert NEW_TABLES <= _tables(r._be)
    assert r._be.raw.execute("PRAGMA user_version").fetchone()[0] == 7


def test_ws_default_seeded():
    r = _reg()
    row = r._be.query_one("SELECT workspace_id,status FROM workspaces WHERE workspace_id=?",
                          ("ws-default",))
    assert row and dict(row)["status"] == "active"


def test_existing_account_backfilled_into_ws_default():
    # the backfill SELECT binds any pre-existing (pre-v7) account to ws-default on open
    r = _reg()
    r.upsert_account("111122223333", now_epoch=1000)
    cnapp_backend._seed_default_workspace(r._be)             # simulate a subsequent open
    row = r._be.query_one("SELECT workspace_id FROM workspace_accounts WHERE account_id=?",
                          ("111122223333",))
    assert row and dict(row)["workspace_id"] == "ws-default"


def test_seed_idempotent():
    r = _reg()
    r.upsert_account("111122223333", now_epoch=1000)
    cnapp_backend._seed_default_workspace(r._be)
    cnapp_backend._seed_default_workspace(r._be)
    ws = dict(r._be.query_one("SELECT COUNT(*) c FROM workspaces WHERE workspace_id='ws-default'"))["c"]
    binds = dict(r._be.query_one("SELECT COUNT(*) c FROM workspace_accounts WHERE account_id='111122223333'"))["c"]
    assert ws == 1 and binds == 1


def test_usage_events_dedup_unique():
    r = _reg()
    cols = ("workspace_id,account_id,metric,event_key,quantity,period,event_epoch,event_iso")
    vals = "('ws-default','a','scan.completed','job-1',1,'2026-07',1,'x')"
    r._be.execute(f"INSERT INTO usage_events({cols}) VALUES {vals} ON CONFLICT DO NOTHING")
    res = r._be.execute(f"INSERT INTO usage_events({cols}) VALUES {vals} ON CONFLICT DO NOTHING")
    assert res.rowcount == 0                                 # second insert deduped
    cnt = dict(r._be.query_one("SELECT COUNT(*) c FROM usage_events WHERE event_key='job-1'"))["c"]
    assert cnt == 1


def test_postgres_ddl_twins_present_and_house_rules():
    ddl = "\n".join(dia.POSTGRES_DDL)
    for t in NEW_TABLES:
        assert f"CREATE TABLE IF NOT EXISTS {t}" in ddl
    assert "created_at BIGINT NOT NULL" in ddl                # epoch twins
    assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in ddl
    # no BOOLEAN anywhere in the multi-tenancy twin blocks
    mt = [s for s in dia.POSTGRES_DDL if "workspace" in s or "usage_events" in s or "platform_admins" in s]
    assert "BOOLEAN" not in "\n".join(mt)
