"""Unit tests for aws_state_dialect — the pure Postgres/SQLite dialect layer:
URL parsing, qmark->pyformat conversion, ON CONFLICT upsert building, the hybrid
row shim, DDL parity, and the postgresql://-fails-open wiring in aws_state.open."""
import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import aws_state
import aws_state_dialect as d


# ── URL parsing ───────────────────────────────────────────────────────────────
@pytest.mark.parametrize("url,scheme,dsn", [
    ("postgresql://u:p@host/db", "postgres", "postgresql://u:p@host/db"),
    ("postgres://host/db", "postgres", "postgres://host/db"),
    ("sqlite:///state.db", "sqlite", "state.db"),
    ("sqlite:////abs/state.db", "sqlite", "/abs/state.db"),
    ("./local.db", "sqlite", "./local.db"),
    (":memory:", "sqlite", ":memory:"),
    ("", "sqlite", ""),
])
def test_parse_state_url(url, scheme, dsn):
    assert d.parse_state_url(url) == (scheme, dsn)


# ── qmark -> pyformat ────────────────────────────────────────────────────────
def test_qmark_to_pyformat_basic():
    assert d.qmark_to_pyformat("SELECT * FROM t WHERE a=? AND b=?") == \
        "SELECT * FROM t WHERE a=%s AND b=%s"


def test_qmark_to_pyformat_escapes_literal_percent():
    assert d.qmark_to_pyformat("WHERE x LIKE '50%' AND y=?") == \
        "WHERE x LIKE '50%%' AND y=%s"


def test_qmark_to_pyformat_skips_question_in_string():
    assert d.qmark_to_pyformat("WHERE note='what?' AND a=?") == \
        "WHERE note='what?' AND a=%s"


# ── upsert building ───────────────────────────────────────────────────────────
def test_upsert_do_update():
    sql = d.build_upsert("findings", ["account", "finding_key", "status"],
                         ["account", "finding_key"], ["status"])
    assert "INSERT INTO findings" in sql
    assert "ON CONFLICT (account, finding_key) DO UPDATE SET status=EXCLUDED.status" in sql


def test_upsert_do_nothing_when_update_none():
    sql = d.build_upsert("scan_coverage", ["scan_id", "account", "region", "check_id"],
                         ["scan_id", "account", "region", "check_id"], None)
    assert "ON CONFLICT" in sql and "DO NOTHING" in sql


def test_upsert_reset_cols_zeroes_drift_counters():
    # the scans-row trap: INSERT OR REPLACE resets drift counters; the PG upsert
    # must reset them too, else stale counts survive a re-scan.
    sql = d.build_upsert("scans", ["scan_id", "posture_score", "new_count"],
                         ["scan_id"], ["posture_score"],
                         reset_cols={"new_count": "0"})
    assert "posture_score=EXCLUDED.posture_score" in sql
    assert "new_count=0" in sql


def test_upsert_returning():
    sql = d.build_upsert("waivers", ["match_type", "approver"], ["id"], ["approver"],
                         returning="id")
    assert sql.rstrip().endswith("RETURNING id")


# ── hybrid row ───────────────────────────────────────────────────────────────
def test_hybrid_row_positional_and_named_and_dict():
    r = d._Row(["account", "status", "n"], ["111", "open", 5])
    assert r[0] == "111"            # positional (COUNT(*).fetchone()[0] style)
    assert r["status"] == "open"    # by name
    assert r.get("missing", "def") == "def"
    assert dict(r) == {"account": "111", "status": "open", "n": 5}
    assert r.keys() == ["account", "status", "n"]
    assert len(r) == 3


# ── DDL parity ────────────────────────────────────────────────────────────────
def test_postgres_ddl_has_all_tables():
    ddl = " ".join(d.PostgresDialect().ddl())
    for t in ("findings", "finding_events", "waivers", "scans", "scan_coverage",
              "principal_usage", "schema_migrations"):
        assert f"TABLE IF NOT EXISTS {t}" in ddl


def test_postgres_ddl_epoch_is_bigint_and_identity():
    ddl = " ".join(d.PostgresDialect().ddl())
    assert "first_seen_epoch BIGINT" in ddl                  # 2038-safe
    assert "GENERATED BY DEFAULT AS IDENTITY" in ddl          # not AUTOINCREMENT
    assert "posture_score DOUBLE PRECISION" in ddl


def test_sqlite_dialect_ddl_matches_state_module():
    stmts = d.SqliteDialect().ddl()
    joined = " ".join(stmts)
    assert "CREATE TABLE IF NOT EXISTS findings" in joined
    assert "AUTOINCREMENT" in joined                          # sqlite keeps its form


def test_dialect_for():
    assert isinstance(d.dialect_for("postgres"), d.PostgresDialect)
    assert isinstance(d.dialect_for("sqlite"), d.SqliteDialect)


# ── fail-open wiring into aws_state.open ─────────────────────────────────────
def test_open_postgres_url_raises_backend_unavailable():
    # postgresql:// must raise (scanner then runs stateless) — NEVER a local sqlite
    with pytest.raises(d.StateBackendUnavailable):
        aws_state.open("postgresql://user@localhost/cnapp")


def test_open_sqlite_url_still_works():
    store = aws_state.open("sqlite:///:memory:") if False else aws_state.open(":memory:")
    assert store is not None
    store.close()


def test_migrate_requires_psycopg():
    # psycopg absent in CI -> raises StateBackendUnavailable, never a silent no-op
    with pytest.raises((d.StateBackendUnavailable, NotImplementedError)):
        d.migrate_sqlite_to_postgres(":memory:", "postgresql://x/y")


def test_build_upsert_empty_update_cols_is_do_nothing():
    """An empty update list must render DO NOTHING, never 'DO UPDATE SET ' (invalid)."""
    import aws_state_dialect as D
    sql = D.build_upsert("accounts", ["account_id", "alias"], ["account_id"], [], ph="?")
    assert "DO NOTHING" in sql and "DO UPDATE SET" not in sql
    # reset_cols with empty update still renders a valid DO UPDATE SET
    sql2 = D.build_upsert("scans", ["scan_id", "crit"], ["scan_id"], [], reset_cols={"crit": "0"})
    assert "DO UPDATE SET crit=0" in sql2
