#!/usr/bin/env python3
"""Generate docs/CIS_DATABASE_INVENTORY.md — the OverWatch half of the CIS Database map.

    python scripts/cis_db_inventory.py

WHY THIS EXISTS SEPARATELY FROM THE MAPPING. Mapping OverWatch onto the CIS AWS Database
Services Benchmark is a join between two lists: the benchmark's 98 recommendations, and
what this product already asserts about the same ten services. Only the first half needs
the benchmark document. This generates the second half, so the mapping pass is a join
rather than a from-scratch inventory — and so the "already covered" column of that map is
derived from the catalogue rather than from somebody's recollection of it.

GENERATED. Do not hand-edit the output; change a check and re-run this. The precedent is
`scripts/check_firing.py`, and the reason is the same: a table maintained by hand next to
a catalogue that moves is a table that quietly stops being true.
"""
from __future__ import annotations

import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from engine import aws_finding_detail as D                          # noqa: E402
from engine.aws_live_scanner import CHECK_SEVERITY as S             # noqa: E402
from engine import aws_cis_db                                       # noqa: E402

#: Benchmark section -> the check-id families that speak to it, with the recommendation
#: COUNT from the benchmark's own table of contents. The count is a reference to the
#: source document (a number, not its text); every description below is generated from
#: this product's own catalogue.
SECTIONS = [
    ("2", "Aurora", 11, ["AUR"]),
    ("3", "RDS", 14, ["RDS"]),
    ("4", "DynamoDB", 9, ["DDB"]),
    ("5", "ElastiCache", 13, ["ELC"]),
    ("6", "MemoryDB", 7, ["MDB"]),
    ("7", "DocumentDB", 12, ["DOCDB"]),
    ("8", "Keyspaces", 4, ["KS"]),
    ("9", "Neptune", 11, ["NEP"]),
    ("10", "Timestream", 10, ["TS"]),
    ("11", "QLDB", 7, ["QLDB"]),
]

HEADER = """# CIS AWS Database Services Benchmark — the OverWatch side of the map

**GENERATED by `scripts/cis_db_inventory.py`. Do not hand-edit.**

This is half of the mapping, and the half that needs no source document: what OverWatch
already asserts about the ten services the benchmark covers. **The other half is now
done** — see [`CIS_DATABASE_BENCHMARK.md`](CIS_DATABASE_BENCHMARK.md) for all 98
recommendations and the check that answers each, and `engine/aws_cis_db_map.py` for the
mapping as data. This file remains the per-check view: the benchmark document is organised
by recommendation, and this one by what OverWatch ships.

The "Proven" column comes from `docs/CHECK_FIRING.md`: `yes` means the suite drives the
check to a real FAIL. A check that runs but has never failed is not evidence of coverage,
which is the distinction that whole document exists to keep.

> **On the source document.** CIS Benchmarks may not be redistributed and the PDF is not
> in this repository. What is cited here is a section number and a recommendation COUNT,
> both references; every description is generated from this product's own catalogue.
"""


def _firing_buckets():
    path = os.path.join(ROOT, "docs", "CHECK_FIRING.md")
    if not os.path.exists(path):
        return set(), set()
    t = io.open(path, encoding="utf-8").read()

    def bucket(name):
        if f"## {name}" not in t:
            return set()
        body = t.split(f"## {name}", 1)[1]
        body = re.split(r"^## ", body, 1, flags=re.M)[0]
        return set(re.findall(r"`([A-Z]{2,10}-\d{2})`", body))

    return bucket("Never observed"), bucket("Runs, but never fails")


def build() -> str:
    never, nofail = _firing_buckets()
    out = [HEADER]
    covered = 0
    recs = 0

    for num, name, count, fams in SECTIONS:
        ids = sorted(c for c in S if c.rsplit("-", 1)[0] in fams)
        recs += count
        covered += len(ids)
        out.append(f"\n## {num} — {name}")
        out.append(f"\n*{count} recommendations in the benchmark. "
                   f"OverWatch ships {len(ids)} check(s) against this service.*\n")
        if not ids:
            out.append("**No checks.** See the decline notes at the foot of this file.\n")
            continue
        out.append("| Check | Severity | Proven to FAIL | What it asserts |")
        out.append("|---|---|---|---|")
        for cid in ids:
            impact = (D.FINDING_DETAIL.get(cid, {}).get("impact") or "").strip()
            impact = impact.replace("|", "/").replace("\n", " ")
            if len(impact) > 160:
                impact = impact[:157].rsplit(" ", 1)[0] + "…"
            state = ("**never observed**" if cid in never else
                     "runs, no FAIL" if cid in nofail else "yes")
            out.append(f"| `{cid}` | {S[cid]} | {state} | {impact} |")
        out.append("")

    out.append(f"\n## Totals\n")
    out.append(f"- **{recs}** recommendations across the ten services.")
    out.append(f"- **{covered}** OverWatch checks speak to those services today.")
    out.append("- The two numbers are NOT comparable: one check can answer several "
               "recommendations, and several recommendations are not decidable at all. "
               "Producing the actual per-recommendation mapping is the point of the "
               "mapping pass; this file is its left-hand column.\n")

    out.append("## Declined, with reasons\n")
    out.append("Recorded as data in `engine/aws_cis_db.py` so this file and the coverage "
               "test read the same list.\n")
    for key, reason in sorted(aws_cis_db.NOT_DETERMINABLE.items()):
        out.append(f"- **`{key}`** — {reason}\n")
    for key, reason in sorted(aws_cis_db.DECLINED_AS_NOT_A_FINDING.items()):
        out.append(f"- **`{key}`** *(readable, judged not a finding)* — {reason}\n")
    return "\n".join(out)


def main() -> int:
    path = os.path.join(ROOT, "docs", "CIS_DATABASE_INVENTORY.md")
    io.open(path, "w", encoding="utf-8", newline="\n").write(build())
    print(f"wrote {os.path.relpath(path, ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
