import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, it, expect } from 'vitest'
import { evaluate, parse, WQLError, WQL_MAX_HOPS, WQL_MAX_LIMIT } from './wql'
import type { GraphFull } from '../api/types'

// The TS WQL engine (SAMPLE mode) must return byte-identical rows to aws_wql.py (the live hub),
// else a saved query yields different results offline vs online. The guard is a SHARED fixture
// generated by scripts/gen_wql_parity.py: the Python engine is the oracle, and every case here
// is replayed through the TS engine and asserted equal. Regenerate the fixture (and this stays
// green) whenever aws_wql.py changes; tests/test_wql_parity.py fails if the fixture drifts.
interface ParityCase { name: string; query: unknown; expected: { count: number; nodes: unknown[] } }
interface Parity { graph: GraphFull; cases: ParityCase[] }
const FX: Parity = JSON.parse(
  readFileSync(join(process.cwd(), 'src', 'lib', '__fixtures__', 'wql_parity.json'), 'utf-8'))

describe('wql.ts == aws_wql.py on the shared parity fixture', () => {
  it('has a non-trivial battery (guards against an empty fixture passing vacuously)', () => {
    expect(FX.cases.length).toBeGreaterThanOrEqual(30)
    expect(FX.graph.nodes.length).toBeGreaterThan(0)
  })

  for (const c of FX.cases) {
    it(`case: ${c.name}`, () => {
      expect(evaluate(c.query, FX.graph)).toEqual(c.expected)
    })
  }

  it('every case reproduces the oracle count exactly', () => {
    for (const c of FX.cases) {
      const got = evaluate(c.query, FX.graph)
      expect(got.count).toBe(c.expected.count)
      expect(got.nodes.length).toBe(c.expected.count)
    }
  })
})

// The single most important trap: the (kind,id) tie-break must be Unicode code-point, NOT
// localeCompare (which folds case). Called out explicitly so a regression names itself.
describe('deterministic code-point ordering (matches Python str<)', () => {
  it('orders IAM roles AdminRole < Zeus < apollo (A=0x41 < Z=0x5A < a=0x61)', () => {
    const ids = evaluate({ kind: 'IAMRole' }, FX.graph).nodes.map((n) => (n as { id: string }).id)
    expect(ids).toEqual([
      'arn:aws:iam::1:role/AdminRole', 'arn:aws:iam::1:role/Zeus', 'arn:aws:iam::1:role/apollo',
    ])
  })
})

// Parser rejection is the security boundary — mirror tests/test_wql.py's parametrized set so a
// TS-side loosening (e.g. accepting a non-whitelisted prop) fails here too, not just in Python.
describe('parse() rejects malformed / unsafe queries', () => {
  const bad: unknown[] = [
    { select: 'edge' },
    { nonsense: 1 },
    { kind: 5 },
    { where: { pred: 'nope' } },
    { where: { pred: 'prop', field: 'arbitrary', op: 'eq', value: 1 } },
    { where: { pred: 'prop', field: 'severity', op: 'regex', value: 'x' } },
    { where: { op: 'not', of: [{ pred: 'crown_jewel' }, { pred: 'crown_jewel' }] } },
    { where: { op: 'and', of: [] } },
    { limit: 0 },
    { limit: -3 },
    { max_hops: 0 },
    { where: { pred: 'reaches', target: 'moon' } },
    { where: { pred: 'reachable_from', target: 'vpc' } },
    { where: { pred: 'has_edge', dir: 'sideways', kind: 'HAS_ROLE' } },
    null,
    [1, 2, 3],
    // explicit null must reject exactly as Python dict.get does (own() mirror), not default away
    { select: null },
    { limit: null },
    { max_hops: null },
    { where: { pred: 'kind', op: null, value: 'S3Bucket' } },
    { where: { pred: 'has_edge', kind: 'HAS_ROLE', dir: null } },
  ]
  for (const q of bad) {
    it(`rejects ${JSON.stringify(q)}`, () => {
      expect(() => parse(q)).toThrow(WQLError)
    })
  }

  it('rejects a predicate tree deeper than WQL_MAX_DEPTH (clean throw, not a RangeError)', () => {
    let pred: unknown = { pred: 'crown_jewel' }
    for (let i = 0; i < 40; i++) pred = { op: 'not', of: [pred] }
    expect(() => parse({ where: pred })).toThrow(WQLError)
  })

  it('rejects a boolean of[] wider than WQL_MAX_PREDS', () => {
    const of = Array.from({ length: 140 }, () => ({ pred: 'crown_jewel' }))
    expect(() => parse({ where: { op: 'or', of } })).toThrow(WQLError)
  })

  it('accepts a well-formed query and clamps limit/max_hops', () => {
    const q = parse({ limit: 99999, max_hops: 999 })
    expect(q.limit).toBe(WQL_MAX_LIMIT)
    expect(q.max_hops).toBe(WQL_MAX_HOPS)
  })
})
